### ISSUE TITLE
Problem with sorting by type and owner

### ISSUE THREAD

**Issue by galdralag** [lxde/pcmanfm-qt#459]
When selecting sorting to 'By file type' folders becomes unsorted
Folders should be always sorted by name when sorting mode has meaning only for files

**Comment by tsujan** [comment]
Thanks for the report!

There's a temporary problem that I should mention every time a bug is reported against pcmanfm-qt. I'll add a link to this comment in future.

Users should know this:

@PCMan, the author of pcmanfm-qt, is making fundamental changes to libfm-qt, the basis of pcmanfm-qt, and also to pcmanfm-qt itself. These changes are supposed to fix many problems. Unfortunately, bugs can't be fixed and new features can't be implemented until @PCMan completes his work. I don't know how long it'll take.

**Comment by tsujan** [comment]
This is fixed a long time ago.

**Comment by galdralag** [comment]
It is not fixed. Folders still not sorted when selecting 'By file type' or 'By file size'. Tested on version 0.12.0 in arch linux.
Step to reproduce:
1. go to /etc folder
1. change sorting 'By file type'
2. press f5

**Comment by tsujan** [comment]
As a matter of fact, before your last comment, I'd tested with `/etc` but hadn't paid attention to how folders were ordered -- just seen they were grouped together. You're right. Reopening this.

**Comment by tsujan** [comment]
Actually, there's a bigger problem: When sorting is by file type, not only folders but also other types of files are sorted irregularly inside their groups -- and the same is true when sorting by owner. That was why I hadn't paid attention to sorting inside groups.
